### ISSUE TITLE
adjust height of web component accordingly whether height is or is NOT specified as an inline style

### ISSUE THREAD

**Issue by szymontyburek** [Global-Virtual-Networks/ls-grid#87]
- [ ] base project is held within s_tyburek_component branch
- [ ] currently, if height is NOT specified, bottom two rows from the grid are cutoff

**Comment by MikeSC27** [comment]
JC, footer no longer covers bottom 2 rows and butts under the last row.  Also if inline style to change height is required will now adjust the footer as expressed.
